version: '3'

services:
  apkgenerator:
    restart: always
    image: apkgenerator
    ports:
      - "20000:22"
    volumes:
      - ./workspace:/home/builds
    build:
      context: .
      dockerfile: ./Dockerfile