version: '3'

services:
  apkgenerator:
    restart: always
    image: apkgenerator
    ports:
      - 2122:22
    volumes:
      - ./workspace:/home/builds
    build:
      context: .
      dockerfile: ./Dockerfile